# Generated by Django 4.2.5 on 2024-01-31 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photomaker.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photomaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=photomaker.models.get_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photo maker',
                'verbose_name_plural': 'photos maker',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
