# Generated by Django 4.2.5 on 2024-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photomaker', '0002_photomaker_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomaker',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
