# Generated by Django 4.2.5 on 2024-02-27 02:44

from django.db import migrations, models
import photomaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('photomaker', '0003_alter_photomaker_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photomaker',
            name='file',
            field=models.ImageField(upload_to=photomaker.models.get_upload_path),
        ),
    ]
