# Generated by Django 4.1.7 on 2023-09-21 15:40

import bgremove.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=bgremove.models.get_upload_path)),
                ('output', models.ImageField(upload_to=bgremove.models.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo Upload',
                'verbose_name_plural': 'Photo Uploads',
            },
        ),
    ]
