# Generated by Django 4.2.5 on 2024-02-25 09:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgremove', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='output',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
