# Generated by Django 4.2.5 on 2024-02-25 14:30

import bgremove.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgremove', '0002_alter_photoupload_image_alter_photoupload_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgRemove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=bgremove.models.get_upload_path)),
                ('output', models.ImageField(upload_to=bgremove.models.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Upload',
                'verbose_name_plural': 'Photo Uploads',
            },
        ),
        migrations.DeleteModel(
            name='PhotoUpload',
        ),
    ]
