# Generated by Django 4.2.5 on 2024-02-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgremove', '0003_bgremove_delete_photoupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgremove',
            options={'verbose_name': 'BG Remove', 'verbose_name_plural': 'Photo Uploads'},
        ),
        migrations.AlterField(
            model_name='bgremove',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='bgremove',
            name='output',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
