# Generated by Django 4.2.5 on 2024-03-14 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgremove', '0004_alter_bgremove_options_alter_bgremove_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgremove',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
